spring:
  application:
    name: spring-cloud-node2
server:
  port: 8006
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/