spring:
  application:
    name: spring-boot-customer
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
feign:
  hystrix:
    enabled: true


