spring:
  application:
    name: spring-cloud-node1
server:
  port: 8005
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8000/eureka/,http://admin:admin@peer2:8001/eureka/