spring:
  application:
    name: spring-boot-zuul
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8000/eureka/,http://admin:admin@peer2:8001/eureka/
#配置zuul端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true
#配置路由
zuul:
  routes:
    spring-boot-producer: /producer/**
