spring:
  application:
    name: spring-boot-producer
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8000/eureka/,http://admin:admin@peer2:8001/eureka/